##
## default download config
##
##>>------------------ base download config -------------------->>
save_path: /mnt/share/md/md10/Vedio
max_thread: 0
folderize: true
base_config_path: "config"
platform: "douyin"
login: true

##>>------------------ network download config -------------------->>
headers_config_name: "headers.yml"  # path = [platform] + [headers_config_path]

##>>------------------ download config -------------------->>
download_config_name: "download.yml"