verifyFp: null
type_id: null
live_id: null
room_id: null
sec_user_id: null
version_code: "99.99.99"
app_id: "1128"
X-Bogus: null
live_api: "https://live.douyin.com/webcast/room/web/enter/"
live_api_share: "https://webcast.amemv.com/webcast/room/reflow/info/"
# flv_pull_url: 1-FULL_HD1 2-HD1 3-SD1 4-SD2
flv_clarity: 1
hls_clarity: 1